"""SQLAlchemy declarative base and shared column helpers.

Models are hand-written to mirror the reviewed migrations in
`database/migrations/`. The migrations are the source of truth for the schema
(ADR-012); these classes are the application's typed view of it. A CI drift check
compares the two, so a model that disagrees with the applied schema fails the
build rather than surfacing as a runtime error.
"""

from __future__ import annotations

import datetime as dt
import uuid
from typing import Any, ClassVar

from sqlalchemy import BigInteger, DateTime, MetaData, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from backend.core.ids import uuid7

__all__ = ["Base", "MoneyMinor", "created_at_column", "updated_at_column", "uuid_pk"]

# Naming convention so that autogenerated constraint names match what the
# hand-written SQL produced, which keeps the drift check meaningful.
_NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=_NAMING_CONVENTION)

    # Every `Mapped[datetime]` becomes TIMESTAMPTZ, not a naive TIMESTAMP. The
    # migrations declare these columns as `TIMESTAMPTZ` and the application only
    # ever handles tz-aware datetimes (the `DTZ` lint rule enforces that), so a
    # naive column here is a latent bug: asyncpg refuses to bind an aware value to
    # a naive column, and a value that slipped through would be stored with the
    # server's offset silently assumed. Setting it once on the base means no
    # individual column can forget.
    type_annotation_map: ClassVar[dict[Any, Any]] = {dt.datetime: DateTime(timezone=True)}

    def __repr__(self) -> str:
        # Deliberately shows only the class and primary key. A default repr that
        # dumped every column would print health values and emails into logs and
        # tracebacks — exactly what docs/06 §5 forbids.
        pk = getattr(self, "id", None)
        return f"<{type(self).__name__} id={pk}>"


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUIDv7 primary key, supplied by the application (ADR-009).

    `default=uuid7` means every ORM insert gets a time-ordered id without the
    caller remembering to pass one. The v4 server default remains as a fallback so
    a direct SQL insert still produces an id, but it is not the intended path —
    v4 fragments the index, which is the whole reason for choosing v7.
    """
    return mapped_column(
        primary_key=True,
        default=uuid7,
        server_default=text("gen_random_uuid()"),
    )


def created_at_column() -> Mapped[dt.datetime]:
    return mapped_column(DateTime(timezone=True), server_default=text("now()"), nullable=False)


def updated_at_column() -> Mapped[dt.datetime]:
    return mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        server_onupdate=text("now()"),
        nullable=False,
    )


# Re-exported for models that store money, so the intent (minor units, never
# float — docs/02 §1) is visible at the column definition.
MoneyMinor = BigInteger
